### ISSUE TITLE
Cursor over button widget

### ISSUE THREAD

**Issue by szepeviktor** [siteorigin/so-widgets-bundle#24]
Please consider
```css
a {
cursor: pointer;
}
```
here https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/so-button-widget/css/style.less#L8
