### ISSUE TITLE
Less Guards not working

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/so-widgets-bundle#433]
Hi

I usually work in sass but the the less support in widget creation is too great to pass up. That being said, my less experience is limited.

I cant seem to get [Less Guards](http://lesscss.org/features/#css-guards-feature) to work. Now i dont know if the less compiler only has a subset of features, nor do i know if it is Site Origin made or a third party library.

Neverthe*less* (see what i did there?) the guards feature is in effect an `if` statement and even tho you can move the `if` logic to the php files it would be semantic and preferable to have style related logic in the stylesheet. 

**Example of code that doesn't work in the compiler but should be valid less:**

```less
@margin-spacing: 1;

.inzite-feature-caption  {
  h2 {
    margin: 0;
    padding: 0;
    line-height: 1.3;
    & when (@margin-spacing = 1) {
      margin-bottom: 1rem;
    }
  }
}
```
